### ISSUE TITLE
servant-swagger-ui-0.2.0.2.1.5/dist/build/example/example: To run, pass 'run' argument

### ISSUE THREAD

**Issue by juhp** [phadej/servant-swagger-ui#13]
Testsuite started to fail:

```
Preprocessing test suite 'example' for servant-swagger-ui-0.2.0.2.1.5...
[1 of 1] Compiling Main             ( example/Main.hs, dist/build/example/example-tmp/Main.o )
Linking dist/build/example/example ...
> /tmp/stackage-build8/servant-swagger-ui-0.2.0.2.1.5$ dist/build/example/example
To run, pass 'run' argument
```

**Comment by phadej** [comment]
I don't see how it fails? Does it return non-zero exit code? Locally, `stack test` is happy, as well as `cabal` on travis.

**Comment by juhp** [comment]
I get exit 0 too locally: but what about "To run, pass 'run' argument"?

**Comment by phadej** [comment]
It's an `example` executable, which isn't run (because it doesn't exit). The test is just to see that it compiles. I'll change the text to `"To run example server, pass 'run' argument"`.
