### ISSUE TITLE
There is swagger-ui 3.0

### ISSUE THREAD

**Issue by phadej** [phadej/servant-swagger-ui#27]
For changes in 3.0: https://github.com/swagger-api/swagger-ui/releases/tag/v3.0.0

> Version 3.0 brings a complete rewrite of Swagger-UI in React.js :tada:
>
> What's new?
>
> This version is a rewrite of Swagger-UI from the the ground up. You get the features in previous versions with benefits:
>
> - Built using the latest technologies, based on React.js.
> - Faster than before, handling larger files.
> - Significantly easier to customize and extend.
> - Fresh UI, giving the classic look a modern twist.
> - Smaller overall size of the product.
> - This version will also make it easier for us to support the next versions of the spec. This version of -
> - Swagger-UI supports version 2 of the Swagger Spec/OAS. Support for older versions have been dropped.

Demo: http://petstore.swagger.io/

An update could be a task at ZuriHac. The only question, should we do minor or major bump with this? opinions @fizruk?

**Comment by fizruk** [comment]
I'm ok with either. For my projects minor bump of `servant-swagger-ui` would be fine.
