### ISSUE TITLE
Swagger UI does not work when nested

### ISSUE THREAD

**Issue by fizruk** [phadej/servant-swagger-ui#8]
Example:

```haskell
type SwaggerSchemaEndpoint = "swagger.json" :> Get '[JSON] Swagger

type NestedAPIWithSwagger
     = SwaggerSchemaEndpoint
  :<|> SwaggerUI "docs" SwaggerSchemaEndpoint NestedApiPlaceholder
  :<|> NestedAPI

type API
    = "nested" :> NestedAPIWithSwagger
 :<|> Raw
```

This does not work since Swagger UI requests http://example.com/swagger.json and not http://example.com/nested/swagger.json

I have tried this:

```haskell
type NestedAPIWithSwagger
     = SwaggerSchemaEndpoint
  :<|> SwaggerUI "docs" ("nested" :> SwaggerSchemaEndpoint) NestedApiPlaceholder
  :<|> NestedAPI
```

but this results in a type error since `"nested" :> SwaggerSchemaEndpoint` is not part of `NestedAPIWithSwagger`.

I think we could fix `SwaggerUI` to request `swagger.json` relative to its root, since necessary information is available in the request. However I am not sure how hard it would be to implement.

**Comment by phadej** [comment]
The design ideas here, is that I'd like `SwaggerUI` not to serve `swagger.json`, as in some cases you don't want to serve ui, but want to server `swagger.json`.

Currently `SwaggerUI` assumes that `api` given to it is the root api, as it's the only assumption it can make. That boils down to how to make `safeLink` to work with nested apis.

For your case you could try:

```hs
type NestedAPIWithSwagger
     = SwaggerSchemaEndpoint
  :<|> SwaggerUI "docs" ("nested" :> SwaggerSchemaEndpoint) ("nested" :> NestedApiPlaceholder)
  :<|> NestedAPI
```

**Comment by fizruk** [comment]
I see.

Should we then add `SwaggerSchemaUI`? It would serve schema too and since we would know it's relative location we would be able to serve `Html` using relative URI `"../swagger.json"`. However, although it works for me, I am not sure http://example.com/nested/docs/../swagger.json is considered equivalent to http://example.com/nested/swagger.json.

Another approach could be instead of assuming that `NestedAp` is a root API, to assume `SwaggerUI` is at the top of `NestedApi` and `SwaggerSchemaEndpoint` is relative to `NestedApi`. Then in server handler for `SwaggerUiHtml` we could retrieve URI from the request, cut from the end and prepend to `SwaggerSchemaEndpoint` URI:
- received request to http://example.com/nested/docs/index.html;
- cut URI to `/nested/` (drop `docs/index.html` at the end);
- prepend to `swagger.json` to get `/nested/swagger.json` URI.

What do you think?

**Comment by phadej** [comment]
yes, that could be added so that script in `index.html` "mangles" the url.

Yet, as we on this, it would be great to come with version which knows where it's served from. So assets could be delivered (`http://example.com/ui` and `http://example.com/ui/` are different when you use relative paths.). Or can `servant` be forced to redirect to with-trailing-slash version?
