### ISSUE TITLE
Difficulty running example

### ISSUE THREAD

**Issue by RocketPuppy** [phadej/servant-swagger-ui#9]
I've downloaded and tried running the example here: https://github.com/phadej/servant-swagger-ui/blob/master/example/Main.hs. I'm seeing multiple requests to fetch the static assets all ending in 404s. Does the servant-swagger-ui library come packaged with the assets, or do I need to download them and place them somewhere to be served. If they need downloaded and served, where do they need to go?

**Comment by RocketPuppy** [comment]
Ha! Got it. When I visit `localhost:8000/ui` I just see the two input boxes and labels and see all the 404's for the other assets. But when I visit `localhost:8000/ui/index.html` then I get all the assets and everything's nice and pretty. I'm not sure if that's a bug or intended, but the README shows a screenshot without the index.html.

**Comment by fizruk** [comment]
@RocketPuppy it should work with [http://localhost:8000/ui/](http://localhost:8000/ui/) (note trailing slash).
Without trailing slash it tries to load resources from root (one level higher then they are).

In theory we could add JS code fixing `window.location.href` when trailing slash is absent.

@phadej what do you think?

**Comment by phadej** [comment]
Hmm, JS side fix would be great!

**Comment by phadej** [comment]
Fixed. Will do a a release after we figure out #8
